name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    uses: ./.github/workflows/build-And-Test-Reusable.yml

  docker-ci:
    needs: build_and_test
    uses: ./.github/workflows/dockerCI-Reusable.yml