name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    uses: ./.github/workflows/build-And-Test-Reusable.yml

  docker-ci:
    needs: build and test
    uses: ./.github/workflows/dockerCI-Reusable.yml