name: Push to GHCR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  java-test:
    uses: ./.github/workflows/build-And-Test-Reusable.yml # Uses the reusable build and test

  build-and-push:
    needs: java-test #Happens after running tests succesfully
    runs-on: ubuntu-latest
    permissions:
      contents: read  #Is allowed to read the contents of the program
      packages: write #Can create a package (maven package) of the program
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} #Uses a github token

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # No idea what the following is
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}} 

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: . #Selects everything in the project
          push: true #Yes, we want to push everything
          tags: ${{ steps.meta.outputs.tags }} #Tags from previous step
          labels: ${{ steps.meta.outputs.labels }} #Labels from previous step (Are there any???)